LootTable = {}

-- money
LootTable[1] = {itemID = 1, name = "Money", description = "Ordinary means of payment.", icon = nil, stats = nil, chance = 100, quality = nil, costs = 1, color = {r = 220, g = 180, b = 90}, slot = nil, class = nil, stackable = false, instance = LootMoney_S}

-- potions
LootTable[2] = {itemID = 2, name = "Heal Potion", description = "Useful healing potion that will restore your life by 30%.", icon = "Icons|Items|1", stats = {health = 30, mana = 0}, chance = 100, quality = "normal", costs = 25, color = {r = 220, g = 90, b = 90}, slot = nil, class = nil, stackable = true, instance = LootPotion_S}
LootTable[3] = {itemID = 3, name = "Mana Potion", description = "Useful mana potion that will restore your mana by 30%.", icon = "Icons|Items|2", stats = {health = 0, mana = 30}, chance = 100, quality = "normal", costs = 25, color = {r = 90, g = 90, b = 220}, slot = nil, class = nil, stackable = true, instance = LootPotion_S}

-- clothes
-- ## HATS ## --
LootTable[100] = {itemID = 100, name = "Hat of Stamina", description = "This hat increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|3", stats = {stamina = 3, intelligence = 0, armor = 100, crit = 0}, chance = 95, quality = "normal", costs = 15, color = {r = 180, g = 180, b = 180}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[101] = {itemID = 101, name = "Hat of Stamina", description = "This hat increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|3", stats = {stamina = 6, intelligence = 0, armor = 300, crit = 0}, chance = 75, quality = "advanced", costs = 100, color = {r = 45, g = 180, b = 45}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[102] = {itemID = 102, name = "Hat of Stamina", description = "This hat increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|3", stats = {stamina = 9, intelligence = 0, armor = 600, crit = 0}, chance = 55, quality = "good", costs = 500, color = {r = 90, g = 90, b = 220}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[103] = {itemID = 103, name = "Hat of Stamina", description = "This hat increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|3", stats = {stamina = 12, intelligence = 0, armor = 900, crit = 0}, chance = 15, quality = "fantastic", costs = 4000, color = {r = 150, g = 65, b = 255}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[104] = {itemID = 104, name = "Hat of Stamina", description = "This hat increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|3", stats = {stamina = 15, intelligence = 0, armor = 1200, crit = 0}, chance = 5, quality = "epic", costs = 7500, color = {r = 255, g = 90, b = 45}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}

LootTable[105] = {itemID = 105, name = "Hat of Intelligence", description = "This hat increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|3", stats = {stamina = 0, intelligence = 3, armor = 100, crit = 0}, chance = 95, quality = "normal", costs = 15, color = {r = 180, g = 180, b = 180}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[106] = {itemID = 106, name = "Hat of Intelligence", description = "This hat increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|3", stats = {stamina = 0, intelligence = 6, armor = 300, crit = 0}, chance = 75, quality = "advanced", costs = 100, color = {r = 45, g = 180, b = 45}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[107] = {itemID = 107, name = "Hat of Intelligence", description = "This hat increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|3", stats = {stamina = 0, intelligence = 9, armor = 600, crit = 0}, chance = 55, quality = "good", costs = 500, color = {r = 90, g = 90, b = 220}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[108] = {itemID = 108, name = "Hat of Intelligence", description = "This hat increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|3", stats = {stamina = 0, intelligence = 12, armor = 900, crit = 0}, chance = 15, quality = "fantastic", costs = 4000, color = {r = 150, g = 65, b = 255}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[109] = {itemID = 109, name = "Hat of Intelligence", description = "This hat increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|3", stats = {stamina = 0, intelligence = 15, armor = 1200, crit = 0}, chance = 5, quality = "epic", costs = 7500, color = {r = 255, g = 90, b = 45}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}

LootTable[110] = {itemID = 110, name = "Hat of Critical", description = "This hat increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|3", stats = {stamina = 0, intelligence = 0, armor = 100, crit = 3}, chance = 95, quality = "normal", costs = 15, color = {r = 180, g = 180, b = 180}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[111] = {itemID = 111, name = "Hat of Critical", description = "This hat increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|3", stats = {stamina = 0, intelligence = 0, armor = 300, crit = 6}, chance = 75, quality = "advanced", costs = 100, color = {r = 45, g = 180, b = 45}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[112] = {itemID = 112, name = "Hat of Critical", description = "This hat increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|3", stats = {stamina = 0, intelligence = 0, armor = 600, crit = 9}, chance = 55, quality = "good", costs = 500, color = {r = 90, g = 90, b = 220}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[113] = {itemID = 113, name = "Hat of Critical", description = "This hat increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|3", stats = {stamina = 0, intelligence = 0, armor = 900, crit = 12}, chance = 15, quality = "fantastic", costs = 4000, color = {r = 150, g = 65, b = 255}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[114] = {itemID = 114, name = "Hat of Critical", description = "This hat increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|3", stats = {stamina = 0, intelligence = 0, armor = 1200, crit = 15}, chance = 5, quality = "epic", costs = 7500, color = {r = 255, g = 90, b = 45}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}

LootTable[115] = {itemID = 115, name = "Hat of Armory", description = "This hat increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|3", stats = {stamina = 1, intelligence = 1, armor = 200, crit = 1}, chance = 95, quality = "normal", costs = 15, color = {r = 180, g = 180, b = 180}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[116] = {itemID = 116, name = "Hat of Armory", description = "This hat increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|3", stats = {stamina = 2, intelligence = 2, armor = 600, crit = 2}, chance = 75, quality = "advanced", costs = 100, color = {r = 45, g = 180, b = 45}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[117] = {itemID = 117, name = "Hat of Armory", description = "This hat increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|3", stats = {stamina = 4, intelligence = 4, armor = 1200, crit = 4}, chance = 55, quality = "good", costs = 500, color = {r = 90, g = 90, b = 220}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[118] = {itemID = 118, name = "Hat of Armory", description = "This hat increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|3", stats = {stamina = 6, intelligence = 6, armor = 1800, crit = 6}, chance = 15, quality = "fantastic", costs = 4000, color = {r = 150, g = 65, b = 255}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[119] = {itemID = 119, name = "Hat of Armory", description = "This hat increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|3", stats = {stamina = 8, intelligence = 8, armor = 2400, crit = 8}, chance = 5, quality = "epic", costs = 7500, color = {r = 255, g = 90, b = 45}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}

LootTable[120] = {itemID = 120, name = "Hat of Mixery", description = "This hat increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|3", stats = {stamina = 2, intelligence = 2, armor = 150, crit = 2}, chance = 95, quality = "normal", costs = 8, color = {r = 180, g = 180, b = 180}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[121] = {itemID = 121, name = "Hat of Mixery", description = "This hat increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|3", stats = {stamina = 3, intelligence = 3, armor = 400, crit = 3}, chance = 75, quality = "advanced", costs = 80, color = {r = 45, g = 180, b = 45}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[122] = {itemID = 122, name = "Hat of Mixery", description = "This hat increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|3", stats = {stamina = 5, intelligence = 5, armor = 800, crit = 5}, chance = 55, quality = "good", costs = 400, color = {r = 90, g = 90, b = 220}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[123] = {itemID = 123, name = "Hat of Mixery", description = "This hat increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|3", stats = {stamina = 8, intelligence = 8, armor = 1000, crit = 8}, chance = 15, quality = "fantastic", costs = 2000, color = {r = 150, g = 65, b = 255}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}
LootTable[124] = {itemID = 124, name = "Hat of Mixery", description = "This hat increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|3", stats = {stamina = 10, intelligence = 10, armor = 1500, crit = 10}, chance = 5, quality = "epic", costs = 3500, color = {r = 255, g = 90, b = 45}, slot = "head", class = nil, stackable = false, instance = LootClothes_S}

-- ## JACKETS ## --
LootTable[200] = {itemID = 200, name = "Jacket of Stamina", description = "This jacket increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|4", stats = {stamina = 5, intelligence = 0, armor = 200, crit = 0}, chance = 95, quality = "normal", costs = 35, color = {r = 180, g = 180, b = 180}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[201] = {itemID = 201, name = "Jacket of Stamina", description = "This jacket increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|4", stats = {stamina = 8, intelligence = 0, armor = 500, crit = 0}, chance = 75, quality = "advanced", costs = 500, color = {r = 45, g = 180, b = 45}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[202] = {itemID = 202, name = "Jacket of Stamina", description = "This jacket increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|4", stats = {stamina = 12, intelligence = 0, armor = 900, crit = 0}, chance = 55, quality = "good", costs = 700, color = {r = 90, g = 90, b = 220}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[203] = {itemID = 203, name = "Jacket of Stamina", description = "This jacket increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|4", stats = {stamina = 15, intelligence = 0, armor = 1200, crit = 0}, chance = 15, quality = "fantastic", costs = 6000, color = {r = 150, g = 65, b = 255}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[204] = {itemID = 204, name = "Jacket of Stamina", description = "This jacket increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|4", stats = {stamina = 20, intelligence = 0, armor = 2500, crit = 0}, chance = 5, quality = "epic", costs = 11500, color = {r = 255, g = 90, b = 45}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}

LootTable[205] = {itemID = 205, name = "Jacket of Intelligence", description = "This jacket increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 5, armor = 200, crit = 0}, chance = 95, quality = "normal", costs = 35, color = {r = 180, g = 180, b = 180}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[206] = {itemID = 206, name = "Jacket of Intelligence", description = "This jacket increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 8, armor = 500, crit = 0}, chance = 75, quality = "advanced", costs = 500, color = {r = 45, g = 180, b = 45}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[207] = {itemID = 207, name = "Jacket of Intelligence", description = "This jacket increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 12, armor = 900, crit = 0}, chance = 55, quality = "good", costs = 700, color = {r = 90, g = 90, b = 220}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[208] = {itemID = 208, name = "Jacket of Intelligence", description = "This jacket increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 15, armor = 1200, crit = 0}, chance = 15, quality = "fantastic", costs = 6000, color = {r = 150, g = 65, b = 255}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[209] = {itemID = 209, name = "Jacket of Intelligence", description = "This jacket increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 20, armor = 2500, crit = 0}, chance = 5, quality = "epic", costs = 11500, color = {r = 255, g = 90, b = 45}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}

LootTable[210] = {itemID = 210, name = "Jacket of Critical", description = "This jacket increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 0, armor = 200, crit = 5}, chance = 95, quality = "normal", costs = 35, color = {r = 180, g = 180, b = 180}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[211] = {itemID = 211, name = "Jacket of Critical", description = "This jacket increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 0, armor = 500, crit = 8}, chance = 75, quality = "advanced", costs = 500, color = {r = 45, g = 180, b = 45}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[212] = {itemID = 212, name = "Jacket of Critical", description = "This jacket increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 0, armor = 900, crit = 12}, chance = 55, quality = "good", costs = 700, color = {r = 90, g = 90, b = 220}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[213] = {itemID = 213, name = "Jacket of Critical", description = "This jacket increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 0, armor = 1200, crit = 15}, chance = 15, quality = "fantastic", costs = 6000, color = {r = 150, g = 65, b = 255}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[214] = {itemID = 214, name = "Jacket of Critical", description = "This jacket increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 0, armor = 2500, crit = 20}, chance = 5, quality = "epic", costs = 11500, color = {r = 255, g = 90, b = 45}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}

LootTable[215] = {itemID = 215, name = "Jacket of Armory", description = "This jacket increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 0, armor = 400, crit = 0}, chance = 95, quality = "normal", costs = 35, color = {r = 180, g = 180, b = 180}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[216] = {itemID = 216, name = "Jacket of Armory", description = "This jacket increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 0, armor = 1000, crit = 0}, chance = 75, quality = "advanced", costs = 500, color = {r = 45, g = 180, b = 45}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[217] = {itemID = 217, name = "Jacket of Armory", description = "This jacket increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 0, armor = 1800, crit = 0}, chance = 55, quality = "good", costs = 700, color = {r = 90, g = 90, b = 220}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[218] = {itemID = 218, name = "Jacket of Armory", description = "This jacket increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 0, armor = 2400, crit = 0}, chance = 15, quality = "fantastic", costs = 6000, color = {r = 150, g = 65, b = 255}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[219] = {itemID = 219, name = "Jacket of Armory", description = "This jacket increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|4", stats = {stamina = 0, intelligence = 0, armor = 5000, crit = 0}, chance = 5, quality = "epic", costs = 11500, color = {r = 255, g = 90, b = 45}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}

LootTable[220] = {itemID = 220, name = "Jacket of Mixery", description = "This jacket increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|4", stats = {stamina = 3, intelligence = 3, armor = 300, crit = 3}, chance = 95, quality = "normal", costs = 55, color = {r = 180, g = 180, b = 180}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[221] = {itemID = 221, name = "Jacket of Mixery", description = "This jacket increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|4", stats = {stamina = 6, intelligence = 6, armor = 700, crit = 6}, chance = 75, quality = "advanced", costs = 600, color = {r = 45, g = 180, b = 45}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[222] = {itemID = 222, name = "Jacket of Mixery", description = "This jacket increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|4", stats = {stamina = 10, intelligence = 10, armor = 1100, crit = 10}, chance = 55, quality = "good", costs = 900, color = {r = 90, g = 90, b = 220}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[223] = {itemID = 223, name = "Jacket of Mixery", description = "This jacket increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|4", stats = {stamina = 12, intelligence = 12, armor = 1800, crit = 12}, chance = 15, quality = "fantastic", costs = 8000, color = {r = 150, g = 65, b = 255}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}
LootTable[224] = {itemID = 224, name = "Jacket of Mixery", description = "This jacket increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|4", stats = {stamina = 16, intelligence = 16, armor = 3000, crit = 16}, chance = 5, quality = "epic", costs = 15500, color = {r = 255, g = 90, b = 45}, slot = "torso", class = nil, stackable = false, instance = LootClothes_S}

-- ## TROUSERS ## --
LootTable[300] = {itemID = 300, name = "Trousers of Stamina", description = "This trouser increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|5", stats = {stamina = 4, intelligence = 0, armor = 150, crit = 0}, chance = 95, quality = "normal", costs = 25, color = {r = 180, g = 180, b = 180}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[301] = {itemID = 301, name = "Trousers of Stamina", description = "This trouser increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|5", stats = {stamina = 6, intelligence = 0, armor = 500, crit = 0}, chance = 75, quality = "advanced", costs = 300, color = {r = 45, g = 180, b = 45}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[302] = {itemID = 302, name = "Trousers of Stamina", description = "This trouser increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|5", stats = {stamina = 10, intelligence = 0, armor = 800, crit = 0}, chance = 55, quality = "good", costs = 600, color = {r = 90, g = 90, b = 220}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[303] = {itemID = 303, name = "Trousers of Stamina", description = "This trouser increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|5", stats = {stamina = 12, intelligence = 0, armor = 1400, crit = 0}, chance = 15, quality = "fantastic", costs = 5500, color = {r = 150, g = 65, b = 255}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[304] = {itemID = 304, name = "Trousers of Stamina", description = "This trouser increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|5", stats = {stamina = 15, intelligence = 0, armor = 2000, crit = 0}, chance = 5, quality = "epic", costs = 12500, color = {r = 255, g = 90, b = 45}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}

LootTable[305] = {itemID = 305, name = "Trousers of Intelligence", description = "This trouser increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 4, armor = 150, crit = 0}, chance = 95, quality = "normal", costs = 25, color = {r = 180, g = 180, b = 180}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[306] = {itemID = 306, name = "Trousers of Intelligence", description = "This trouser increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 6, armor = 500, crit = 0}, chance = 75, quality = "advanced", costs = 300, color = {r = 45, g = 180, b = 45}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[307] = {itemID = 307, name = "Trousers of Intelligence", description = "This trouser increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 10, armor = 800, crit = 0}, chance = 55, quality = "good", costs = 600, color = {r = 90, g = 90, b = 220}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[308] = {itemID = 308, name = "Trousers of Intelligence", description = "This trouser increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 12, armor = 1400, crit = 0}, chance = 15, quality = "fantastic", costs = 5500, color = {r = 150, g = 65, b = 255}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[309] = {itemID = 309, name = "Trousers of Intelligence", description = "This trouser increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 15, armor = 2000, crit = 0}, chance = 5, quality = "epic", costs = 12500, color = {r = 255, g = 90, b = 45}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}

LootTable[310] = {itemID = 310, name = "Trousers of Critical", description = "This trouser increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 0, armor = 150, crit = 4}, chance = 95, quality = "normal", costs = 25, color = {r = 180, g = 180, b = 180}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[311] = {itemID = 311, name = "Trousers of Critical", description = "This trouser increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 0, armor = 500, crit = 6}, chance = 75, quality = "advanced", costs = 300, color = {r = 45, g = 180, b = 45}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[312] = {itemID = 312, name = "Trousers of Critical", description = "This trouser increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 0, armor = 800, crit = 10}, chance = 55, quality = "good", costs = 600, color = {r = 90, g = 90, b = 220}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[313] = {itemID = 313, name = "Trousers of Critical", description = "This trouser increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 0, armor = 1400, crit = 12}, chance = 15, quality = "fantastic", costs = 5500, color = {r = 150, g = 65, b = 255}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[314] = {itemID = 314, name = "Trousers of Critical", description = "This trouser increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 0, armor = 2000, crit = 15}, chance = 5, quality = "epic", costs = 12500, color = {r = 255, g = 90, b = 45}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}

LootTable[315] = {itemID = 315, name = "Trousers of Armory", description = "This trouser increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 0, armor = 300, crit = 4}, chance = 95, quality = "normal", costs = 25, color = {r = 180, g = 180, b = 180}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[316] = {itemID = 316, name = "Trousers of Armory", description = "This trouser increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 0, armor = 1000, crit = 6}, chance = 75, quality = "advanced", costs = 300, color = {r = 45, g = 180, b = 45}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[317] = {itemID = 317, name = "Trousers of Armory", description = "This trouser increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 0, armor = 1600, crit = 10}, chance = 55, quality = "good", costs = 600, color = {r = 90, g = 90, b = 220}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[318] = {itemID = 318, name = "Trousers of Armory", description = "This trouser increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 0, armor = 2800, crit = 12}, chance = 15, quality = "fantastic", costs = 5500, color = {r = 150, g = 65, b = 255}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[319] = {itemID = 319, name = "Trousers of Armory", description = "This trouser increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|5", stats = {stamina = 0, intelligence = 0, armor = 4000, crit = 15}, chance = 5, quality = "epic", costs = 12500, color = {r = 255, g = 90, b = 45}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}

LootTable[320] = {itemID = 320, name = "Trousers of Mixery", description = "This trouser increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|5", stats = {stamina = 3, intelligence = 3, armor = 350, crit = 3}, chance = 95, quality = "normal", costs = 45, color = {r = 180, g = 180, b = 180}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[321] = {itemID = 321, name = "Trousers of Mixery", description = "This trouser increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|5", stats = {stamina = 4, intelligence = 4, armor = 1200, crit = 4}, chance = 75, quality = "advanced", costs = 500, color = {r = 45, g = 180, b = 45}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[322] = {itemID = 322, name = "Trousers of Mixery", description = "This trouser increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|5", stats = {stamina = 8, intelligence = 8, armor = 1400, crit = 8}, chance = 55, quality = "good", costs = 700, color = {r = 90, g = 90, b = 220}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[323] = {itemID = 323, name = "Trousers of Mixery", description = "This trouser increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|5", stats = {stamina = 10, intelligence = 10, armor = 2000, crit = 10}, chance = 15, quality = "fantastic", costs = 600, color = {r = 150, g = 65, b = 255}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}
LootTable[324] = {itemID = 324, name = "Trousers of Mixery", description = "This trouser increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|5", stats = {stamina = 12, intelligence = 12, armor = 3000, crit = 12}, chance = 5, quality = "epic", costs = 13500, color = {r = 255, g = 90, b = 45}, slot = "legs", class = nil, stackable = false, instance = LootClothes_S}

-- ## SHOES ## --
LootTable[400] = {itemID = 400, name = "Shoes of Stamina", description = "This shoes increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|6", stats = {stamina = 3, intelligence = 0, armor = 100, crit = 0}, chance = 95, quality = "normal", costs = 20, color = {r = 180, g = 180, b = 180}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[401] = {itemID = 401, name = "Shoes of Stamina", description = "This shoes increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|6", stats = {stamina = 6, intelligence = 0, armor = 300, crit = 0}, chance = 75, quality = "advanced", costs = 100, color = {r = 45, g = 180, b = 45}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[402] = {itemID = 402, name = "Shoes of Stamina", description = "This shoes increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|6", stats = {stamina = 9, intelligence = 0, armor = 600, crit = 0}, chance = 55, quality = "good", costs = 600, color = {r = 90, g = 90, b = 220}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[403] = {itemID = 403, name = "Shoes of Stamina", description = "This shoes increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|6", stats = {stamina = 12, intelligence = 0, armor = 900, crit = 0}, chance = 15, quality = "fantastic", costs = 4500, color = {r = 150, g = 65, b = 255}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[404] = {itemID = 404, name = "Shoes of Stamina", description = "This shoes increasing your stamina by a big amount. This will have great affect to your life points.", icon = "Icons|Items|6", stats = {stamina = 15, intelligence = 0, armor = 1200, crit = 0}, chance = 5, quality = "epic", costs = 8000, color = {r = 255, g = 90, b = 45}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}

LootTable[405] = {itemID = 405, name = "Shoes of Intelligence", description = "This shoes increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 3, armor = 100, crit = 0}, chance = 95, quality = "normal", costs = 20, color = {r = 180, g = 180, b = 180}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[406] = {itemID = 406, name = "Shoes of Intelligence", description = "This shoes increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 6, armor = 300, crit = 0}, chance = 75, quality = "advanced", costs = 100, color = {r = 45, g = 180, b = 45}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[407] = {itemID = 407, name = "Shoes of Intelligence", description = "This shoes increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 9, armor = 600, crit = 0}, chance = 55, quality = "good", costs = 600, color = {r = 90, g = 90, b = 220}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[408] = {itemID = 408, name = "Shoes of Intelligence", description = "This shoes increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 12, armor = 900, crit = 0}, chance = 15, quality = "fantastic", costs = 4500, color = {r = 150, g = 65, b = 255}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[409] = {itemID = 409, name = "Shoes of Intelligence", description = "This shoes increasing your intelligence by a big amount. This will have great affect to your mana points.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 15, armor = 1200, crit = 0}, chance = 5, quality = "epic", costs = 8000, color = {r = 255, g = 90, b = 45}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}

LootTable[410] = {itemID = 410, name = "Shoes of Critical", description = "This shoes increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 0, armor = 100, crit = 3}, chance = 95, quality = "normal", costs = 20, color = {r = 180, g = 180, b = 180}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[411] = {itemID = 411, name = "Shoes of Critical", description = "This shoes increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 0, armor = 300, crit = 6}, chance = 75, quality = "advanced", costs = 100, color = {r = 45, g = 180, b = 45}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[412] = {itemID = 412, name = "Shoes of Critical", description = "This shoes increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 0, armor = 600, crit = 9}, chance = 55, quality = "good", costs = 600, color = {r = 90, g = 90, b = 220}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[413] = {itemID = 413, name = "Shoes of Critical", description = "This shoes increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 0, armor = 900, crit = 12}, chance = 15, quality = "fantastic", costs = 4500, color = {r = 150, g = 65, b = 255}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[414] = {itemID = 414, name = "Shoes of Critical", description = "This shoes increasing your crit chance by a big amount. This will have great affect to your critical attack points.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 0, armor = 1200, crit = 15}, chance = 5, quality = "epic", costs = 8000, color = {r = 255, g = 90, b = 45}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}

LootTable[415] = {itemID = 415, name = "Shoes of Armory", description = "This shoes increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 0, armor = 200, crit = 0}, chance = 95, quality = "normal", costs = 20, color = {r = 180, g = 180, b = 180}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[416] = {itemID = 416, name = "Shoes of Armory", description = "This shoes increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 0, armor = 600, crit = 0}, chance = 75, quality = "advanced", costs = 100, color = {r = 45, g = 180, b = 45}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[417] = {itemID = 417, name = "Shoes of Armory", description = "This shoes increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 0, armor = 1200, crit = 0}, chance = 55, quality = "good", costs = 600, color = {r = 90, g = 90, b = 220}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[418] = {itemID = 418, name = "Shoes of Armory", description = "This shoes increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 0, armor = 1800, crit = 0}, chance = 15, quality = "fantastic", costs = 4500, color = {r = 150, g = 65, b = 255}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[419] = {itemID = 419, name = "Shoes of Armory", description = "This shoes increasing your armor by a big amount. This will have great affect by reducing your incoming damage.", icon = "Icons|Items|6", stats = {stamina = 0, intelligence = 0, armor = 2400, crit = 0}, chance = 5, quality = "epic", costs = 8000, color = {r = 255, g = 90, b = 45}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}

LootTable[420] = {itemID = 420, name = "Shoes of Mixery", description = "This shoes increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|6", stats = {stamina = 2, intelligence = 2, armor = 150, crit = 2}, chance = 95, quality = "normal", costs = 20, color = {r = 180, g = 180, b = 180}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[421] = {itemID = 421, name = "Shoes of Mixery", description = "This shoes increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|6", stats = {stamina = 4, intelligence = 4, armor = 400, crit = 4}, chance = 75, quality = "advanced", costs = 100, color = {r = 45, g = 180, b = 45}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[422] = {itemID = 422, name = "Shoes of Mixery", description = "This shoes increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|6", stats = {stamina = 6, intelligence = 6, armor = 800, crit = 6}, chance = 55, quality = "good", costs = 600, color = {r = 90, g = 90, b = 220}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[423] = {itemID = 423, name = "Shoes of Mixery", description = "This shoes increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|6", stats = {stamina = 9, intelligence = 9, armor = 1200, crit = 9}, chance = 15, quality = "fantastic", costs = 4500, color = {r = 150, g = 65, b = 255}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}
LootTable[424] = {itemID = 424, name = "Shoes of Mixery", description = "This shoes increasing all your stats by medium amount. This will have semi affect to all of your activities.", icon = "Icons|Items|6", stats = {stamina = 12, intelligence = 12, armor = 1800, crit = 12}, chance = 5, quality = "epic", costs = 8000, color = {r = 255, g = 90, b = 45}, slot = "feet", class = nil, stackable = false, instance = LootClothes_S}

-- jewelry

-- weapons


function getRandomLoot()
	local tableLength = 0
	
	for index, lootContainer in pairs(LootTable) do
		if (lootContainer) then
			tableLength = tableLength + 1
		end
	end
	
	local randomID = math.random(2, tableLength)
	
	local currentID = 0
	
	for index, lootContainer in pairs(LootTable) do
		if (lootContainer) then
			currentID = currentID + 1
			
			if (currentID == randomID) then
				return lootContainer
			end
		end
	end
end